fix ip resolve

diff --git a/trx-ip b/trx-ip
--- a/trx-ip
+++ b/trx-ip
@@ -1,6 +1,17 @@
 #!/bin/env bash
 
 # IAROM MADDEN mail@iarom.org
+# - [ ] setup ip_res - resolved ip locally file as separate from 'ip_man'
+
+cmd=$1 && shift 1
+
+trx_git_dir="${HOME}/.local/share/aax/trx"
+ssh_cfg_dir="${HOME}/.ssh"
+ipi=$(cat "${ssh_cfg_dir}/host-i" 2>/dev/null)
+ip_git="${trx_git_dir}/host-${ipi}-ip-wlan" # ip shared via git
+ip_man="${ssh_cfg_dir}/host-${ipi}-ip-wlan"
+ip_mac="${ssh_cfg_dir}/host-${ipi}-ip-mac" # gateway interface mac address
+trx_h="/data/data/com.termux/files/home"
 
 
 adb_set() {
@@ -13,15 +24,36 @@ adb_set() {
 # domain resolution
 
 ip_resolv() {
+    ipi="$(ip neigh show default | awk '{print $1}' | head -n1)"
+    ip_resolv_i
+}
+
+ip_resolv_x() {
+    # ssh config fails with ip6 setup
+    ipi="$(ip neigh show default | grep router | awk '{print $1}' | tail -n1)"
+    ip_resolv_i
+}
+
+ip_resolv_y() {
     ipi="$(ip route show default | awk '{print $3}')"
-    [ ! -n "$(ip neighbour show ${ipi} | grep ${ipm})" ] \
-        && { echo "no match with recorded mac address"; exit; }
-    echo "${ipi}" > "${ip_manual}"
+    ip_resolv_i
+}
+
+ip_resolv_i() {
+    [ -n "$(ip neighbour show ${ipi} | grep $(cat ${ip_mac}))" ] \
+        || { echo "no match with recorded mac address"; exit; }
+    echo "ip: ${ipi}"
+    echo "${ipi}" > "${ip_man}"
+}
+
+ip_resolv_mac() {
+    ipm="$(ip neigh show default | grep router | awk '{print $5}' | head -n1)"
+    echo "${ipm}" > "${ip_mac}"
 }
 
 ip_git_pull()   {
     git -C ${trx_git_dir} pull
-    cat ${ip_gitshare} > ${ip_manual} 2>/dev/null
+    cat ${ip_git} > ${ip_man} 2>/dev/null
 }
 
 ip_git_push() {
@@ -30,9 +62,9 @@ ip_git_push() {
         ip=$(ifconfig | grep -Eo 'inet (10\.137\.)[0-9]*\.[0-9]*' | sed -E 's/inet //g')
 
     printf "wlan ip: $ip ---> $ip_gitshare \n"
-    printf "%s" "$ip" > $ip_gitshare
+    printf "%s" "$ip" > $ip_git
     
-    git -C "$trx_git_dir" commit $ip_gitshare -m "wlan update"
+    git -C "$trx_git_dir" commit $ip_git -m "wlan update"
     git -C "$trx_git_dir" push
 }
 
@@ -47,7 +79,7 @@ ip_find() {
         -sn 192.168.64.0/24 \
         -oG - \
         | awk '/Up$/{print $2}' \
-        | head -n 1 $ip_nmap_ls - > $ip_manual
+        | head -n 1 $ip_nmap_ls - > ${ip_man}
     #> $ip_nmap_ls
 }
 
@@ -56,26 +88,25 @@ ip_find_10() {
         -sn 10.137.70.0/24 \
         -oG - \
         | awk '/Up$/{print $2}' \
-        | tail -n 1 $ip_nmap_ls - > $ip_manual
+        | tail -n 1 $ip_nmap_ls - > ${ip_man}
     #> $ip_nmap_ls
 }
 
 case $cmd in
-  # ip
-    ip-echo|echo)         echo "${ipi}" ;;
-    ip-echo-git)          echo "${ipy}" ;;
-    ip-set-manual)        echo "$1" > $ip_manual ;;
-    ip|ip-resolv)         ip_resolv ;;
-    ip-git-pull)          ip_git_pull ;;
-    ip-git-push)          ip_git_push ;;
-    ip-ssh-push)          ip_ssh_push ;;
-    ip-find-nmap)         ip_find ;;
-    adb|ip-adb)           adb_set ;;
-
+    eh|echo-host)        echo ${ipi} ;;
+    e|echo-man)          echo $(cat "${ip_man}") ;;
+    eg|echo-git)         echo $(cat "${ip_git}") ;;
+    em|echo-mac)         echo $(cat "${ip_mac}") ;;
+    s|set-manual)        echo "${1}" > ${ip_man} ;;
+    m|set-mac)           ip_resolv_mac ;;
+    a|r|resolv)          ip_resolv ;;
+    g|git-pull)          ip_git_pull ;;
+    p|git-push)          ip_git_push ;;
+    ssh-push)            ip_ssh_push ;;
+    resolv-nmap)         ip_find ;;
+    adb)                 adb_set ;;
 esac
 
 # - [ ] consider dns hook upon networkmanager event for connecting 
 # to hotspot, to resolve gateway ip with hostname and inject
 # reduces complexity of current ssh proxycommand method and external script 
-
-
